# Storyboards
ib:
    inputs: ../
    outputs:
       - templateName: scenes-swift4
         output: StoryboardScenes.swift
       - templateName: segues-swift5
         output: StoryboardSegues.swift

# Localization
strings:
    inputs: ../Resources/Localizable.strings
    outputs:
        - templateName: structured-swift4
          output: Strings.swift

# Images & Colors
xcassets:
    inputs: ../Resources/Assets.xcassets
    outputs:
        - templateName: swift4
          output: Assets.swift

